embedding_size: 64
learning_rate_scheduler: [0.96, 50]
learning_rate: 0.001

n_ui_layers: 7
n_layers: 1
knn_k: 10
tau: 0.5
cl_loss: 0.01
embloss_weight: 0.1
feat_embed_dim: 64
reg_weight: 1e-04
n_hyper_layer: 4
keep_rate: 0.7
alpha: 0.05

hyper_num: 32
hc_loss_weight: 1e-05
ghc_weight: 0.01
hyper_parameters: [""]

# hyper_num: [4,8,16,32,64,128]
# hc_loss_weight: [1e-06,5e-06,1e-05,5e-05,1e-04]
# ghc_weight: [0.001,0.005,0.01,0.05,0.1]
# hyper_parameters: ["hyper_num","hc_loss_weight","embloss_weight","ghc_weight"]